# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Maryam Sobhani'

# Site footer
footer:
  copyright:
    notice: 'Â© {year} Maryam Sobhani. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'January 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
hugoblox:
  theme:
    pack: synthwave
    colors_light:
      primary: gray
    colors:
      primary: blue
    mode: dark
  typography:
    size: lg
    font: serif
  layout:
    spacing: compact
  identity:
    name: Maryam Sobhani
    tagline: Political Scientist | International Relations
    description: Maryam Sobhani is a Political Scientist, specializing in International Relations with a strong interest in the Middle East and Human Rights.
  content:
    citations:
      style: chicago
  seo:
    title: Maryam Sobhani | Politican Scientist | International Relations
    location:
      address:
        street: 1333 Powell St.
        city: Emeryville
        region: CA
        postal_code: "94608"
        country: US
      phone: +1 520 477 1007
